[package]
name = "axuspace"
version = "0.1.0"
edition = "2024"
authors = ["Anekoique <ctolu01@gmail.com>"]

[dependencies]
axerrno = "0.1"
memory_addr = "0.4"
percpu = "0.2"
page_table_multiarch = "0.5.5"
